-- Command Dashboard — Supabase schema.
-- Run this once in Supabase → SQL Editor. Safe to re-run (uses IF NOT EXISTS).

create table if not exists public.meta (
  key text primary key,
  value boolean not null
);

create table if not exists public.admins (
  id text primary key,
  code text not null,
  name text not null,
  username text unique not null,
  password_hash text not null
);

create table if not exists public.employees (
  id text primary key,
  code text not null,
  name text not null,
  username text unique not null,
  password_hash text not null,
  shift_slot text check (shift_slot in ('morning', 'afternoon', 'night')),
  assigned_place text,
  on_duty boolean not null default false,
  last_location jsonb,
  last_check_in jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  token text primary key,
  user_id text not null,
  role text not null check (role in ('admin', 'employee')),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists sessions_expires_at_idx on public.sessions (expires_at);

-- The server connects with the service_role key, which bypasses Row Level
-- Security entirely — RLS is enabled anyway as defence in depth in case the
-- anon/public key is ever used against these tables by mistake.
alter table public.meta enable row level security;
alter table public.admins enable row level security;
alter table public.employees enable row level security;
alter table public.sessions enable row level security;
-- No policies are created, so the anon/authenticated roles get zero access
-- (only service_role, which bypasses RLS, can read or write).

-- Private bucket for check-in photos. The app serves them through a signed
-- URL generated by the server, so no public/anon access is granted here.
insert into storage.buckets (id, name, public)
values ('checkin-photos', 'checkin-photos', false)
on conflict (id) do nothing;
